Metrics/LineLength:
  Max: 120
  AllowURI: true

Metrics/MethodLength:
  Max: 15

Style/SpaceInsideParens:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/ClassLength:
  Max: 125
