AllCops:
  NewCops: disable

Metrics/LineLength:
  Max: 120
  AllowURI: true

Metrics/MethodLength:
  Max: 15

Style/SpaceInsideParens:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/ClassLength:
  Max: 130

# TODO: Remove each of the rules below once fixed.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Encoding:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false